<?php

namespace CallOfBeer\ApiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CobEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CobEventRepository extends EntityRepository
{
}
