<?php

namespace CallOfBeer\ApiBundle\Entity;

/**
 * EventUserRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventUserRoleRepository extends \Doctrine\ORM\EntityRepository
{
	public function getByEventAndUser($id_event, $id_user)
    {
        return $this->createQueryBuilder()
            ->field('user')->equals($id_event)
            ->field('event')->equals($id_event)
            ->getQuery()->getSingleResult();
    }
}
