version: "2"
services:
  callofbeer:
    image: debian:jessie
    volumes:
      - ./:/app
    tty: true

  nginx:
    build: docker/nginx
    ports:
      - "8085:80"
    links:
      - php-fpm
    volumes:
      - ./:/app
   
  php-fpm:
    build: docker/php-fpm
    volumes_from:
      - callofbeer
    working_dir: /app
    links:
      - mysql
      - elasticsearch

  mysql:
    image: mysql:5.7
    volumes:
      - "./.data/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ezrtdryfghujcosdkfhbuinzdgxfnvuiyuhdoinyzgveuftgy
      MYSQL_DATABASE: callofbeer
      MYSQL_USER: callofbeer
      MYSQL_PASSWORD: callofbeer

  elasticsearch:
    image: elasticsearch:1.5