services:
    callofbeer_user.user_created:
        class: CallOfBeer\UserBundle\EventListener\UserCreatedListener
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: kernel.event_subscriber }