fos_elastica:
    clients:
        default: { host: %elastic_host%, port: %elastic_port% }
    serializer: ~
    indexes:
        callofbeer: 
            types:
                event:
                    mappings: 
                        name: { boost: 5 }
                        date: { type: date, boost: 3 }
                        address:
                            type: "nested"
                            properties:
                                name: { boost: 4 }
                                address: { boost: 2 }
                                zip: { boost: 3 }
                                city: { boost: 3 }
                                country: { boost: 1 }
                                lat: { boost: 1 }
                                lon: { boost: 1 }
                                geolocation: { type: geo_point }
                                private: ~
                    persistence:
                        driver: orm # orm, mongodb, propel are available
                        model:  CallOfBeer\ApiBundle\Entity\CobEvent
                        provider: ~
                        listener: ~
                        finder: ~
                    serializer:
                        groups: [elastica, Default]