call_of_beer_user:
    resource: "@CallOfBeerUserBundle/Resources/config/routing.yml"
    prefix:   /

call_of_beer_api:
    resource: "@CallOfBeerApiBundle/Resources/config/routing.yml"
    prefix:   /

#API Rest Rooting
rest : 
    type : rest
    resource : "routing_rest.yml"
    prefix : /

