security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        cob_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # main:
        #     pattern: ^/
        #     form_login:
        #         provider: cob_userbundle
        #         csrf_provider: form.csrf_provider
        #     logout:       true
        #     anonymous:    true

        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false
            stateless:    true

        oauth_authorize:
            pattern:    ^/oauth/v2/auth
            form_login:
                provider: cob_userbundle
                check_path: /oauth/v2/auth_login_check
                login_path: /oauth/v2/auth_login
            logout:       true
            anonymous:    true

        api:
            pattern:    ^/
            logout:     true
            fos_oauth:  true
            stateless:  true
            anonymous:  true # can be omitted as its default value

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }