blog_show:
    path:   /api/address
    defaults:  { _controller: CallOfBeerApiBundle:Geocoding:getAddress }

geocoding:
    path:   /geoloc
    defaults:  { _controller: CallOfBeerApiBundle:Geocoding:getGeoloc }