events : 
  type: rest
  resource:		"CallOfBeerApiBundle:Event"
  name_prefix:  api_

geocoding : 
  type: rest
  resource:		"CallOfBeerApiBundle:Geocoding"
  name_prefix:  api_

users : 
  type: rest
  resource:		"CallOfBeerApiBundle:User"
  name_prefix:  api_
