call_of_beer_o_auth_login:
    path:     /oauth/v2/auth_login
    defaults: { _controller: CallOfBeerOAuthBundle:Security:login }

call_of_beer_o_auth_login_check:
    path:     /oauth/v2/auth_login_check
    defaults: { _controller: CallOfBeerOAuthBundle:Security:loginCheck }

call_of_beer_o_auth_logout:
    path:     /oauth/v2/auth/logout
    defaults: { _controller: CallOfBeerOAuthBundle:Security:logout }